on: [push, pull_request]
name: ci

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Run Rustfmt (run `cargo fmt --all` to fix)
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --all-targets --all-features
